language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
script: bundle exec rake spec
gemfile:
  - gemfiles/rails52.gemfile
  - gemfiles/rails6.gemfile
notifications:
  email:
    - support@travellink.com.au
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
